// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQFRA0kBg7Kf0-szSS2lmMiBQA5QNf4c',
    appId: '1:404454871210:web:0492d27eec063db59a80d3',
    messagingSenderId: '404454871210',
    projectId: 'scrole-2682f',
    authDomain: 'scrole-2682f.firebaseapp.com',
    storageBucket: 'scrole-2682f.firebasestorage.app',
    measurementId: 'G-V5KN6HNZRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC20bPIh0A7FSstlSUPZRnzuzj7X9RpEtI',
    appId: '1:404454871210:android:e6ee6dbc11e63e629a80d3',
    messagingSenderId: '404454871210',
    projectId: 'scrole-2682f',
    storageBucket: 'scrole-2682f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvUimXkQ23AmKrGsOocSpAQ71xh6ORDSc',
    appId: '1:404454871210:ios:929a729e7e791ba69a80d3',
    messagingSenderId: '404454871210',
    projectId: 'scrole-2682f',
    storageBucket: 'scrole-2682f.firebasestorage.app',
    iosBundleId: 'com.example.scrole',
  );
}
